spring.application.name=placement-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/placement_db
spring.datasource.username=root
spring.datasource.password=WJ28@krhps

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

file.upload-dir=uploads/resumes

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB